name: xai_model_explanation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - streamlit
  - cv2
  - grad-cam
  - pip
  - notebook
  - jupyterlab
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - altair
